packages/matrix-identity-server/src/3pid/bind.ts, packages/matrix-identity-server/src/3pid/index.ts, packages/matrix-identity-server/src/3pid/unbind.ts, packages/matrix-identity-server/src/db/index.test.ts, packages/matrix-identity-server/src/db/index.ts, packages/matrix-identity-server/src/db/sql/pg.ts, packages/matrix-identity-server/src/db/sql/sql.ts, packages/matrix-identity-server/src/db/sql/sqlite.ts, packages/matrix-identity-server/src/index.test.ts, packages/matrix-identity-server/src/index.ts, packages/matrix-identity-server/src/terms/index.post.ts, packages/matrix-identity-server/src/utils.ts, packages/matrix-identity-server/src/validate/email/requestToken.ts, packages/matrix-identity-server/src/validate/email/submitToken.ts
Merge establishing association with new branch since the previous had unsolvable conflicts.
=> Merge establishing association with new branch

package-lock.json, packages/crypto/src/index.test.ts, packages/crypto/src/index.ts, packages/matrix-identity-server/package.json, packages/matrix-identity-server/src/db/index.ts, packages/matrix-identity-server/src/ephemeral_signing/index.ts, packages/matrix-identity-server/src/index.test.ts, packages/matrix-identity-server/src/index.ts, packages/matrix-identity-server/src/invitation/index.ts, packages/matrix-identity-server/templates/3pidInvitation.tpl
=> Draft : added store-invite and sing-ed25519

packages/matrix-client-server/src/admin/whois.ts, packages/matrix-client-server/src/index.test.ts, packages/matrix-client-server/src/index.ts, packages/matrix-client-server/src/utils/userInteractiveAuthentication.ts
Added new endpoint /whois from the spec : https://spec.matrix.org/v1.11/client-server-api/#notes-on-identity-servers
=> Client server whois

packages/matrix-client-server/src/devices/changeDevices.ts, packages/matrix-client-server/src/devices/getDevices.ts, packages/matrix-client-server/src/index.test.ts, packages/matrix-client-server/src/index.ts
Developped the following APIs and their tests :
https://spec.matrix.org/v1.11/client-server-api/#put_matrixclientv3devicesdeviceid
https://spec.matrix.org/v1.11/client-server-api/#get_matrixclientv3devicesdeviceid
https://spec.matrix.org/v1.11/client-server-api/#get_matrixclientv3devices
=> feat: get and put methods for device related APIs developped and tested

packages/matrix-client-server/src/__testData__/buildUserDB.ts, packages/matrix-client-server/src/__testData__/matrixDbTestConf.json, packages/matrix-client-server/src/index.test.ts, packages/matrix-client-server/src/index.ts, packages/matrix-client-server/src/matrixDb/index.ts, packages/matrix-client-server/src/types.ts, packages/matrix-client-server/src/user/rooms/getRoomAccountData.ts, packages/matrix-client-server/src/user/rooms/putRoomAccountData.ts, packages/matrix-client-server/src/utils/userInteractiveAuthentication.ts
Added two endpoints from the spec : https://spec.matrix.org/v1.11/client-server-api/#get_matrixclientv3useruseridroomsroomidaccount_datatype and https://spec.matrix.org/v1.11/client-server-api/#get_matrixclientv3useruseridroomsroomidaccount_datatype
=> get/put account_data in a room

packages/matrix-client-server/src/index.test.ts, packages/matrix-client-server/src/index.ts, packages/matrix-client-server/src/rooms/room_information/room_aliases.ts
Added endpoint for : 
https://spec.matrix.org/v1.11/client-server-api/#get_matrixclientv3roomsroomidaliases
=> Client server/room aliases

packages/matrix-client-server/src/rooms/room_information/get_joined_rooms.ts, packages/matrix-client-server/src/rooms/rooms.test.ts
Fixed function and tests (information was sought in the wrong table of the synapses database)
=> fix: fixed getjoined rooms function

packages/matrix-client-server/src/rooms/roomId/getEventId.ts, packages/matrix-client-server/src/rooms/roomId/getJoinedMembers.ts, packages/matrix-client-server/src/rooms/roomId/getTimestampToEvent.ts, packages/matrix-client-server/src/rooms/rooms.test.ts, packages/matrix-identity-server/src/db/index.test.ts, packages/matrix-identity-server/src/db/sql/pg.ts, packages/matrix-identity-server/src/db/sql/sqlite.ts
Eslint malfunctioned because of old vscode version. Corrected files I had worked on where eslint errors were remaining
=> chore : eslint

packages/matrix-identity-server/src/index.test.ts, packages/matrix-identity-server/src/invitation/index.ts, packages/matrix-identity-server/src/lookup/index.ts
Fixed store-invite : removed call to self in fetch(/lookup), and corrected other mistakes and related tests
=> feat : fixed store-invite with fetch to self and other mistakes

.compose/haproxy/haproxy.cfg, Dockerfile, docker-compose.yml, packages/matrix-identity-server/src/db/sql/_createTables.ts, packages/matrix-identity-server/src/index.ts, packages/tom-server/src/identity-server/utils/authenticate.ts, packages/tom-server/src/vault-api/middlewares/auth.test.ts, packages/utils/src/utils.ts, server.mjs
Fix to check for remote access_token
=> Fix matrix authentication

packages/matrix-identity-server/src/db/index.ts
=> ✨ implement longterm keypairs creation in database

packages/matrix-identity-server/src/db/index.ts, packages/matrix-identity-server/src/index.test.ts, packages/matrix-identity-server/src/invitation/index.ts
=> 🎨 use long term keypairs in invitation token creation

packages/matrix-identity-server/src/3pid/bind.ts, packages/matrix-identity-server/src/db/index.test.ts, packages/matrix-identity-server/src/db/index.ts, packages/matrix-identity-server/src/types.ts, packages/matrix-identity-server/src/utils.test.ts, packages/matrix-identity-server/src/utils.ts
=> ✨implement 3pid binding invite hook ( #158 ) 

docker-compose.yml, packages/federated-identity-service/src/config.json, packages/matrix-identity-server/src/invitation/index.ts, packages/matrix-identity-server/src/types.ts, packages/matrix-identity-server/src/utils/sms-service.test.ts, packages/matrix-identity-server/src/utils/sms-service.ts
- update SMS service
- improve docker-compose
- improve default config
- fix pepper fetching in store-invite API
=> 🎨 improvements

nx.json
=> Update nx.json to use the new NX organisation offering us free cache

packages/matrix-client-server/server.mjs, packages/matrix-identity-server/server.mjs, packages/tom-server/src/invitation-api/middlewares/index.ts, packages/tom-server/src/utils/services/email-service.ts, server.mjs
- update email service
- enforce phone checking
- better parse of SMTP config
=> 🔧 invitation API delivery updates

landing/package.json, landing/tsconfig.json, packages/federated-identity-service/src/config.json, server.mjs
- use vite + Remix CreateRequestHandler
- better parse boolean ENV vars
- update landing package to be a module
- add missing config in federated identity server
=> 🔧 TOM improvements

packages/tom-server/src/invitation-api/services/index.ts, packages/tom-server/src/invitation-api/tests/controller.test.ts, packages/tom-server/src/invitation-api/tests/middleware.test.ts, packages/tom-server/src/invitation-api/tests/service.test.ts, packages/tom-server/src/invitation-api/types.ts
- update invitation expiration type to `int` instead of `string`
=> 🎨 Invitation expiration fix

packages/matrix-identity-server/src/db/index.ts, packages/tom-server/src/invitation-api/controllers/index.ts, packages/tom-server/src/invitation-api/middlewares/index.ts, packages/tom-server/src/invitation-api/services/index.ts, packages/tom-server/src/invitation-api/tests/controller.test.ts, packages/tom-server/src/invitation-api/tests/service.test.ts, packages/tom-server/src/invitation-api/types.ts, packages/tom-server/src/utils.ts, packages/tom-server/src/utils/middlewares/cookie-auth.middleware.ts
=> ✨ indicate the matrix user that accepted the invitation ( #224 )

packages/tom-server/src/invitation-api/services/index.ts, packages/tom-server/src/invitation-api/tests/service.test.ts
=> 🐛 created room is now marked as direct message ( #2302 #236 )

packages/tom-server/src/identity-server/index.ts, packages/tom-server/src/identity-server/lookup/_search.ts
When `ADDITIONAL_FEATURES` is off: only returns addressbook entries
=> feat: always allows `lookup/match`

packages/tom-server/src/identity-server/index.ts, packages/tom-server/src/identity-server/lookup/_search.ts, packages/tom-server/src/index.ts, server.mjs
Using the existing helper to properly handle the ADDITIONAL_FEATURES env flag.
=> ✨ Parse additional features env flag
